=== folio-org/lib-linked-data-rdf4ld/src/main/resources/mappingProfile/model/schema/edgeMapping.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Resource Edge mapping definition",
  "type": "object",
  "properties": {
    "resourceMapping": {
      "$ref": "resourceMapping.json"
    },
    "fetchRemote": {
      "type": "boolean"
    },
    "bfNameSpace": {
      "type": "string",
      "description": "Bibframe resource name space"
    },
    "ldResourceDef": {
      "$ref": "ldResourceDef.json"
    },
    "bfResourceDef": {
      "$ref": "bfResourceDef.json"
    }
  }
}

=== folio-org/lib-linked-data-rdf4ld/src/main/resources/mappingProfile/Instance_Bibframe_2.0.json
{
  "bfResourceDef": {
    "typeSet": "http://id.loc.gov/ontologies/bibframe/Instance"
  },
  "bfNameSpace": "http://id.loc.gov/ontologies/bibframe/instances/",
  "ldResourceDef": {
    "typeSet": "INSTANCE"
  },
  "resourceMapping": {
    "properties": [
      {
        "ldProperty": "DIMENSIONS",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/dimensions"
      },
      {
        "ldProperty": "STATEMENT_OF_RESPONSIBILITY",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/responsibilityStatement"
      }
    ],
    "outgoingEdges": [
      {
        "resourceMapping": {
          "properties": [
            {
              "ldProperty": "MAIN_TITLE",
              "bfProperty": "http://id.loc.gov/ontologies/bibframe/mainTitle"
            },
            {
              "ldProperty": "SUBTITLE",
              "bfProperty": "http://id.loc.gov/ontologies/bibframe/subtitle"
            }
          ],
          "label": [ "MAIN_TITLE", "SUBTITLE"]
        },
        "bfNameSpace": "http://id.loc.gov/sources/titles/",
        "ldResourceDef": {
          "typeSet": "TITLE",
          "predicate": "TITLE"
        },
        "bfResourceDef": {
          "typeSet": "http://id.loc.gov/ontologies/bibframe/Title",
          "predicate": "http://id.loc.gov/ontologies/bibframe/title"
        }
      },
      {
        "resourceMapping": {
          "properties": [
            {
              "ldProperty": "MAIN_TITLE",
              "bfProperty": "http://id.loc.gov/ontologies/bibframe/mainTitle"
            },
            {
              "ldProperty": "SUBTITLE",
              "bfProperty": "http://id.loc.gov/ontologies/bibframe/subtitle"
            }
          ],
          "label": [ "MAIN_TITLE", "SUBTITLE"]
        },
        "bfNameSpace": "http://id.loc.gov/sources/titles/",
        "ldResourceDef": {
          "typeSet": "VARIANT_TITLE",
          "predicate": "TITLE"
        },
        "bfResourceDef": {
          "typeSet": "http://id.loc.gov/ontologies/bibframe/VariantTitle",
          "predicate": "http://id.loc.gov/ontologies/bibframe/title"
        }
      }
    ],
    "incomingEdges": [
      {
        "resourceMapping": {
          "properties": [
            {
              "ldProperty": "LABEL",
              "bfProperty": "http://www.w3.org/2000/01/rdf-schema#label"
            }
          ]
        },
        "bfNameSpace": "http://id.loc.gov/ontologies/bibframe/works/",
        "ldResourceDef": {
          "typeSet": "WORK",
          "predicate": "INSTANTIATES"
        },
        "bfResourceDef": {
          "typeSet": "http://id.loc.gov/ontologies/bibframe/Work",
          "predicate": "http://id.loc.gov/ontologies/bibframe/instanceOf"
        }
      }
    ]
  }
}

=== folio-org/lib-linked-data-rdf4ld/src/main/resources/mappingProfile/bibframe2.0/title_variant.json
{
  "bfNameSpace": "http://id.loc.gov/sources/titles/",
  "ldResourceDef": {
    "typeSet": "VARIANT_TITLE",
    "predicate": "TITLE"
  },
  "bfResourceDef": {
    "typeSet": "http://id.loc.gov/ontologies/bibframe/VariantTitle",
    "predicate": "http://id.loc.gov/ontologies/bibframe/title"
  },
  "resourceMapping": {
    "properties": [
      {
        "ldProperty": "MAIN_TITLE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/mainTitle"
      },
      {
        "ldProperty": "PART_NAME",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/partName"
      },
      {
        "ldProperty": "PART_NUMBER",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/partNumber"
      },
      {
        "ldProperty": "SUBTITLE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/subtitle"
      },
      {
        "ldProperty": "DATE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/date"
      },
      {
        "ldProperty": "NOTE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/note"
      },
      {
        "ldProperty": "VARIANT_TYPE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/variantType"
      }
    ],
    "label": [
      "MAIN_TITLE",
      "SUBTITLE"
    ]
  }
}

=== folio-org/lib-linked-data-rdf4ld/src/main/resources/mappingProfile/bibframe2.0/title.json
{
  "bfNameSpace": "http://id.loc.gov/resources/titles/",
  "ldResourceDef": {
    "typeSet": "TITLE",
    "predicate": "TITLE"
  },
  "bfResourceDef": {
    "typeSet": "http://id.loc.gov/ontologies/bibframe/Title",
    "predicate": "http://id.loc.gov/ontologies/bibframe/title"
  },
  "resourceMapping": {
    "properties": [
      {
        "ldProperty": "MAIN_TITLE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/mainTitle"
      },
      {
        "ldProperty": "PART_NAME",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/partName"
      },
      {
        "ldProperty": "PART_NUMBER",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/partNumber"
      },
      {
        "ldProperty": "SUBTITLE",
        "bfProperty": "http://id.loc.gov/ontologies/bibframe/subtitle"
      },
      {
        "ldProperty": "NON_SORT_NUM",
        "bfProperty": "http://id.loc.gov/ontologies/bflc/nonSortNum"
      }
    ],
    "label": [
      "MAIN_TITLE",
      "SUBTITLE"
    ]
  }
}
